name: Test CQRS Dig

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'

      - name: Download Modules
        shell: bash
        run: go mod tidy

      - name: Build Package
        shell: bash
        run: go build

      - name: Test Package
        shell: bash
        run: go test